# -*- coding: utf-8 -*-
"""Countries_And_Tweets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11TQGQsII_pTS1NM-Rjlki5tIQkoafSxS
"""

# Commented out IPython magic to ensure Python compatibility.
# %config Completer.use_jedi = False
# %config IPCompleter.greedy=True

!pip install geocoder

import tweepy
import os
import numpy as np
import matplotlib.pyplot as plt
import json
import sys
import geocoder
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
from PIL import Image

consumer_key = "b5vvACInTiIQlL5Rygxq51rFP"
consumer_secret = "XsChwSSw88AXLB2dTOBAY0FcPyi2Ts4Cph5HIwPqEWZk1Rgqy6"
access_token = '1188456148883529728-dC9cY0fPs5JyV70QgRPBJrdd9VSHrH'
access_token_secret = '00VfZgu8WHDZlCNHGPKhnIrSUcIG0how0BJktMPJNrxYN'
callback_uri = 'oob'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret, callback_uri)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

available_loc = api.trends_available()
available_loc

for code in available_loc:
    print(code['country'])

def getWOEIDCode(country, available_loc):
    for code in available_loc:
        if code['country'] == country:
            return code['parentid']

getWOEIDCode('Germany', available_loc)

def getTrendString(woeid, api):
    trends = api.trends_place(woeid)
    words = [trend['name'] for trend in trends[0]['trends']]
    gen_string = " ".join(x if x[0]!='#' else x[1:] for x in words)
    return gen_string

getTrendString('23424829', api)

for code in available_loc:
    if code['name'] == '23424977':
        print(code['woeid'])

!mkdir savedImages

mask = np.array(Image.open("Germany.png").convert('RGB'))

wordcloud = WordCloud(width=1600, height=800, max_font_size=60, background_color="white", mode="RGBA", max_words=2000, mask=mask).generate(getTrendString('23424829', api))

# create coloring from image
image_colors = ImageColorGenerator(mask)
fig = plt.figure(figsize=(20,10), facecolor='w')
plt.subplot(1,2,2)
plt.imshow(wordcloud.recolor(color_func=image_colors), interpolation="bilinear")
plt.axis("off")
plt.subplot(1,2,1)
plt.imshow(mask)
plt.axis("off")
plt.title("Germany", fontsize=30)
plt.show()

def showTrendingTweetsInCountry(country, api):
    
    mask = np.array(Image.open(f"{country}.png").convert('RGB'))
    country_woeid = getWOEIDCode(country, available_loc)
    country_trends_string = getTrendString(country_woeid, api)
    
    wordcloud = WordCloud(width=1600, height=800, max_font_size=60, background_color="white", mode="RGBA", max_words=2000, mask=mask).generate(country_trends_string)

    # create coloring from image
    image_colors = ImageColorGenerator(mask)
    plt.figure(figsize=(20,10), facecolor='w')
    plt.subplot(1,2,2)
    plt.imshow(wordcloud.recolor(color_func=image_colors), interpolation="bilinear")
    plt.axis("off")
    plt.subplot(1,2,1)
    plt.imshow(mask)
    plt.axis("off")
    plt.title(f"{country}", fontsize=30)
    plt.savefig(f"savedImages/{country}-Trending-Topics.png")
    plt.show()

showTrendingTweetsInCountry('Germany', api)

showTrendingTweetsInCountry('India', api)

showTrendingTweetsInCountry('Ireland', api)

showTrendingTweetsInCountry('Canada', api)

showTrendingTweetsInCountry('Russia', api)

showTrendingTweetsInCountry('United Kingdom', api)

showTrendingTweetsInCountry('Italy', api)

showTrendingTweetsInCountry('Australia', api)

showTrendingTweetsInCountry('Netherlands', api)

showTrendingTweetsInCountry('Indonesia', api)

showTrendingTweetsInCountry('Nigeria', api)

showTrendingTweetsInCountry('United States', api)

showTrendingTweetsInCountry('Venezuela', api)

showTrendingTweetsInCountry('France', api)

showTrendingTweetsInCountry('Ukraine', api)

showTrendingTweetsInCountry('Spain', api)

showTrendingTweetsInCountry('Mexico', api)

showTrendingTweetsInCountry('Jordan', api)

showTrendingTweetsInCountry('Greece', api)

showTrendingTweetsInCountry('Egypt', api)

showTrendingTweetsInCountry('Japan', api)

showTrendingTweetsInCountry('Singapore', api)

showTrendingTweetsInCountry('Sweden', api)

showTrendingTweetsInCountry('Norway', api)

showTrendingTweetsInCountry('South Africa', api)

showTrendingTweetsInCountry('Puerto Rico', api)

showTrendingTweetsInCountry('Lebanon', api)

showTrendingTweetsInCountry('Argentina', api)

showTrendingTweetsInCountry('Belgium', api)

showTrendingTweetsInCountry('Brazil', api)

showTrendingTweetsInCountry('Chile', api)

showTrendingTweetsInCountry('Ecuador', api)

!zip -r savedImages.zip savedImages

